export const Menus = [
  {
    name: "Home",
    icon: "/assets/home.png",
    dis: "translate-x-0",
    path: "/Home",
    colorName: "pastel-blue",
  },
  {
    name: "Your Library",
    icon: "/assets/book.png",
    dis: "translate-x-16",
    altText: "Search Icon",
    path: "/yourlibrary",
    colorName: "laurel-green",
  },
  {
    name: "Explore",
    icon: "/assets/bell.png",
    dis: "translate-x-32",
    altText: "Notifications Icon",
    path: "/recipesPage",
    colorName: "lemon-meringue",
  },
  {
    name: "Shopping",
    icon: "/assets/shopping-cart.png",
    dis: "translate-x-48",
    altText: "Shopping Cart Icon",
    path: "/shopping",
    colorName: "pastel-pink",
  },
  {
    name: "Profile",
    icon: "/assets/user.png",
    dis: "translate-x-64",
    altText: "User Icon",
    path: "/profile",
    colorName: "copper-orange",
  },
];
