export const Menus = [
  {
    name: "Search",
    icon: "/public/assets/search.png",
    dis: "translate-x-0",
    path: "/Home",
    colorName: "pastel-blue",
  },
  {
    name: "Your Library",
    icon: "/public/assets/book.png",
    dis: "translate-x-16",
    altText: "Search Icon",
    path: "/yourlibrary",
    colorName: "laurel-green",
  },
  {
    name: "Scanner",
    icon: "/public/assets/scanner.png",
    dis: "translate-x-32",
    altText: "Scanner Icon",
    path: "/scanner",
    colorName: "lemon-meringue",
  },
  {
    name: "Shopping",
    icon: "/public/assets/shopping-cart.png",
    dis: "translate-x-48",
    altText: "Shopping Cart Icon",
    path: "/shopping",
    colorName: "pastel-pink",
  },
  {
    name: "Profile",
    icon: "/public/assets/user.png",
    dis: "translate-x-64",
    altText: "User Icon",
    path: "/profile",
    colorName: "copper-orange",
  },
];
